### ISSUE TITLE
ARM Cortex-M4 (Nuvoton NUC472) not booting with External RAM on EBI Interface

### ISSUE THREAD

**Issue by Ritesh236** [OpenNuvoton/NUC472_442BSP#1]
ARM Cortex-M4 (Nuvoton NUC472) not booting with External RAM on EBI Interface

Hi,

We are working on ARM Cortex-M4 (Nuvoton NUC472) based SoC as per our requirement.We are facing one critical issue like board is not booting when we enabled and used extrenal RAM on EBI.

We have ported following BSP package with below toolchain for NUC472.

- BSP version : 3.03.000 (Downloaded from https://github.com/OpenNuvoton/NUC472_442BSP)

- Tool-chain Version : arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release).

We have created bare framework with above BSP and we are able to start the board with existing ld script provided in BSP with internal RAM support.

Now, We have added the support for external RAM of 512KB on EBI in linker script as per our requirement to move few libraries into external RAM.So, We have added one test library and placed in external ram to validate and test external RAM with our bare build.
But, Board does not starts if we make any variable as extern to use from library which is placed into external RAM.

It is working fine If we are putting that library into internal RAM then board gets up and running without any stuck up issue.

Please find following CFLAGS and LDFLAGS options which we are using into our compilation support.

CFLAGS :
-mcpu=cortex-m4
-mthumb
-mfpu=fpv4-sp-d16
-mfloat-abi=hard
-g2
-Wall
-c
-DNUC442RI8AE
-D__FPU_USED -std=c99
-ffunction-sections -fdata-sections
-fstrict-volatile-bitfields
-fno-short-enums

LDFLAGS :
-Wl,--gc-sections
-Wl,-static
-Xlinker --no-enum-size-warning
-Xlinker --wrap=_malloc_r
-Xlinker --wrap=_free_r
-Xlinker --wrap=_calloc_r
-Xlinker --wrap=_realloc_r
-Wl,--start-group
-lgcc -lc -lm -lnosys
-Wl,--end-group

Please find following list of libraries which we have moved into external RAM

test library
FreeRTOS Heap Memory

Please find attached sample multi RAM linker script (for reference) and our own sample linker script which we have used into our example

Also, Please find below code execution flow of our sample project on which external RAM on EBI is not working

1) On Board Boot Up, Linker script is calling Reset_Handler from which _start is called
2) after that main function will be called from main.c file of BSP
3) Then it will create Hardware Setup, EBI Init, Data Copy and init heap section
4) After that we have created one sample task to test freeRTOS functionality

So, check above details with linker script and let me know if need any more details from my side regarding same.

- Sample multi RAM linker script (for reference)
[multi-ram.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2663215/multi-ram.txt)

- Our own sample linker script
[gcc_arm_ext_ram.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2663218/gcc_arm_ext_ram.txt)

**Comment by yachen** [comment]
Hi @Ritesh236 ,

You said EBI is initialized after enter the main() function. But maybe you should enable EBI  peripheral clock (CLK_AHBCLK[3]) and multi-function pin config in very early stage of startup_NUC472_442.s so start up code can copy library to EBI SRAM.

Sincerely,

Yi-An Chen

**Comment by Ritesh236** [comment]
> Hi @Ritesh236 ,
> 
> You said EBI is initialized after enter the main() function. But maybe you should enable EBI peripheral clock (CLK_AHBCLK[3]) and multi-function pin config in very early stage of startup_NUC472_442.s so start up code can copy library to EBI SRAM.
> 
> Sincerely,
> 
> Yi-An Chen

Hi Yi-An Chen,

Yes. We have also tried with that way like initialize EBI Interface from SystemInit API before main function is called but still facing same issue. 

So, Do you have sample LD script and start up code example with multiple RAM support like we are doing? Also, Would you please check like are we missing any CFLAGS or LDFLAGS as we have mentioned into thread? 

It will be good if you provide example for that so that we can take reference to move further as we are in critical stage right as per current issue.

Let me know if you need any more details from our side regarding same

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

Do you have any update regarding last reply which I have sent for this issue?

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

Is there any update regarding same?

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
Hi,

Does modify start up code help? How do you test EMAC using ext. SRAM if there’s booting issue?
I do not have environment to test this scenario.


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
it seems External RAM on EBI is working fine with this changes https://github.com/OpenNuvoton/NUC472_442BSP/issues/2#issuecomment-449271511

Though it fails to work for certain peripherals or libraries when using alone for application (No Internal SRAM usage except for Boot loader)

**Comment by yachen** [comment]
Close since there's no further discussion for a while. Reopen if necessary.
