### ISSUE TITLE
ARM Toolchain/Linker support for External RAM on EBI Interface

### ISSUE THREAD

**Issue by Ritesh236** [OpenNuvoton/NUC472_442BSP#2]
Hi,

We are working on ARM Cortex-M4 (Nuvoton NUC472) based SoC as per our requirement and we need support to set specific object (.o) or specific library file (.a) into specific section into External RAM on EBI Interface.

So, Would you please provide example with linker script to do it with External RAM?

Let me know if you need any information or details regarding query.

**Comment by Ritesh236** [comment]
Hi @yachen ,

Do you have any sample example with linker script to put specific object (.o) or specific library file (.a) into specific section into External RAM on EBI Interface?

**Comment by yachen** [comment]
Hi @Ritesh236

No, we do not have scatter file for such purpose.
Maybe you can refer to M480’s SampleCode\StdDriver\SPIM_DMM_RUN_CODE\GCC gcc_arm.ld script which put specific code in external SPI flash.
Or NUC505’s SampleCode\BootTemplate\CriticalOnSRAM\GCC\PartialOnSRAM.ld script which relocate critical code to internal memory.


Sincerely,

Yi-An Chen

**Comment by Ritesh236** [comment]
> Hi @Ritesh236 No, we do not have scatter file for such purpose. Maybe you can refer to M480’s SampleCode\StdDriver\SPIM_DMM_RUN_CODE\GCC gcc_arm.ld script which put specific code in external SPI flash. Or NUC505’s SampleCode\BootTemplate\CriticalOnSRAM\GCC\PartialOnSRAM.ld script which relocate critical code to internal memory. Sincerely, Yi-An Chen From: Ritesh236 [mailto:notifications@github.com] Sent: Tuesday, December 11, 2018 12:01 PM To: OpenNuvoton/NUC472_442BSP Cc: MS10 YAChen; Mention Subject: Re: [OpenNuvoton/NUC472_442BSP] ARM Toolchain/Linker support for External RAM on EBI Interface (#2) Hi @yachen<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yachen&d=DwMCaQ&c=ue8mO8zgC4VZ4q_aNVKt8G9MC01UFDmisvMR1k-EoDM&r=yA-2gk543Dr0X9PvbYhMvIWU6V8uKB-QK7a4h58mCfM&m=CdUJ9FSlR2fbcuRLHyQzjPrc4-E_DQCXLRNmF2b2GDQ&s=7HRjqX8p8e-B4IxcUzKYUFdJIEB4JOmWD_y71reIlf0&e=> , Do you have any sample example with linker script to put specific object (.o) or specific library file (.a) into specific section into External RAM on EBI Interface? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenNuvoton_NUC472-5F442BSP_issues_2-23issuecomment-2D446064536&d=DwMCaQ&c=ue8mO8zgC4VZ4q_aNVKt8G9MC01UFDmisvMR1k-EoDM&r=yA-2gk543Dr0X9PvbYhMvIWU6V8uKB-QK7a4h58mCfM&m=CdUJ9FSlR2fbcuRLHyQzjPrc4-E_DQCXLRNmF2b2GDQ&s=dfoRlpiGn2qHd7Y5Osr5PXeWvhDpELEmTMRvockjRcU&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABQn8i0YiU5RGf0I0pFZQGgkLXu-2Du1t5ks5u3y3wgaJpZM4ZLU2h&d=DwMCaQ&c=ue8mO8zgC4VZ4q_aNVKt8G9MC01UFDmisvMR1k-EoDM&r=yA-2gk543Dr0X9PvbYhMvIWU6V8uKB-QK7a4h58mCfM&m=CdUJ9FSlR2fbcuRLHyQzjPrc4-E_DQCXLRNmF2b2GDQ&s=C2vwurNeM50yALxqx7dL9JnK7YWNsJSuuDrtSRPeTsk&e=>. =========================================================================================== The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

Hi @yachen ,

Thanks for quick reply.

Right now, We are focusing to up board with external RAM as per our requirement. But did you check our CFLAGS and LDFLAGS creating any issue while starting board with external RAM as we have described into thread?

So, is it creating any issue with mention parameters to use with external RAM?

**Comment by yachen** [comment]
Hi,

The script seems fine. I didn’t find anything skeptical<https://www.google.com.tw/search?safe=active&rlz=1C1GCEU_zh-TWTW821TW821&q=skeptical&spell=1&sa=X&ved=0ahUKEwjJ7LKDsJffAhVDebwKHecqDagQkeECCCgoAA>.
But I do notice the link script have following section which is comment out. Please follow the description uncomment it, define __STARTUP_COPY_MULTIPLE in startup code and test again.

        /* To copy multiple ROM to RAM sections,
        * uncomment .copy.table section and,
        * define __STARTUP_COPY_MULTIPLE in startup_ARMCMx.S */
        /*
        .copy.table :
        {
                . = ALIGN(4);
                __copy_table_start__ = .;
                LONG (__etext)
                LONG (__data_start__)
                LONG (__data_end__ - __data_start__)
                LONG (__etext2)
                LONG (__data2_start__)
                LONG (__data2_end__ - __data2_start__)
                __copy_table_end__ = .;
        } > FLASH
        */

Sincerely,

Yi-An Chen


===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
Thanks for Reply.

I will check it and let you know if any issue with that

**Comment by Ritesh236** [comment]
Please find overall implementation details https://github.com/OpenNuvoton/NUC472_442BSP/issues/4#issuecomment-449263221

Would you please suggest your above suggestion of copy table work with application having linker both Internal and External RAM together?

It would be good if you can provide any example where we can use Internal and External RAM together  in linker for application while external RAM initialization done into bootloader?

**Comment by yachen** [comment]
Close since there's no further discussion for a while. Reopen if necessary.
