### ISSUE TITLE
Failed to receive complete data from UART Driver

### ISSUE THREAD

**Issue by Ritesh236** [OpenNuvoton/NUC472_442BSP#3]
Hi @yachen ,

We have started to work on Nuvoton NUC472 and taken BSP version : 3.03.000 (Downloaded from https://github.com/OpenNuvoton/NUC472_442BSP) as per our project requirement.

We are using Tool-chain Version : arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release).

So, We have just used bare minimal build with provided BSP, Linker Scripts, Toolchain and sample project to initialize hardware setup and rest of required stuffs.

Then, We have enabled UART3/UART4 into 2 different NUC472 based board and just used UART_Write with buffer size as 64 bytes.

But, We are getting only 16 Bytes to be received over debug console and not getting remaining bytes. So, Do you have any like is there any issue into UART_Write API or do we need to change that code to fulfill that requirement?

Let me know if anyone has faced this type of issue and did some workaround fix for that and let me know if need any more details regarding issue.

**Comment by yachen** [comment]
Hi,

Write function returns after UART FIFO full. Have you check the return value of UART_Write()?

uint32_t UART_Write(UART_T* uart,uint8_t *pu8TxBuf, uint32_t u32WriteBytes)
{
    uint32_t  u32Count;

    for(u32Count=0; u32Count != u32WriteBytes; u32Count++)
    {
        if(uart->FIFOSTS & UART_FIFOSTS_TXFULL_Msk)   /* Wait Tx empty and Time-out manner */
        {
            return u32Count;
        }
        uart->DAT = pu8TxBuf[u32Count];    /* Send UART Data from buffer */
    }

    return u32Count;
}

Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

I will check it and let you know result with that as well

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

We have checked return value of UART_Write() which gives maximum 16 bytes even if we give string more than 16 bytes.

SO I think this might be genuine issue of UART Driver to send more than 16 bytes data or might be need to have some workaround for that.

Would you please check with your SDK Engineer like below code?

```
int ret_code = 0;

ret_code = UART_Write(UART3,"This is testing string for Nuvoton NUC472 Board", strlen("This is testing string for Nuvoton NUC472 Board"));

if (ret == 16)
   while(1);
else
  continue rest code
```

So, We will get Output buffer till 16 characters but we had checked return code and based on that code execution is being processed.

Do you have any idea like is there any changes we are missing into UART Low Level from register point of view to get complete data?

Hope above information will be sufficient for you to understand issue of UART driver. Still let me know if need any more details for this

**Comment by yachen** [comment]
Hi,

UART_Write() return 16 because UART FIFO is full. This API don’t block. Application should call UART_Write() again after there’re space in FIFO.


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
Hi,

So, As peryour comment, UART FIFO size is 16 bytes for NUC472 Hardware? Correct?

So, How it can be managed from application later to write debug print or frame of 128 bytes or more than that? How it will be handled from application side? Do we need to call UART_Write API till it reaches to end of Frame?

Would you please explain one example with sample.code to handle it from application code without changing UART Driver code?

So, It will be helpful for us to keep UART driver BSP code as it is.

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
UART0 has 64-byte FIFO. Others have 16-byte FIFO.
Yes, application need with call UART_Write() with different TX buffer index until it reach the end of frame.


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
HI Yi-An Chen,

We have tried with this way into UART_Write API and it is working fine without any issue.

```
uint32_t UART_Write(UART_T* uart,uint8_t *pu8TxBuf, uint32_t u32WriteBytes)
 {
-    uint32_t  u32Count;
-
-    for(u32Count=0; u32Count != u32WriteBytes; u32Count++)
-    {
-        if(uart->FIFOSTS & UART_FIFOSTS_TXFULL_Msk)   /* Wait Tx empty and Time-out manner */
-        {
-            return u32Count;
-        }
-        uart->DAT = pu8TxBuf[u32Count];    /* Send UART Data from buffer */
-    }
-
-    return u32Count;
+	uint32_t  u32Count, u32delayno=0;
+
+	for(u32Count=0; u32Count != u32WriteBytes; u32Count++)
+	{
+		while((uart->FIFOSTS & UART_FIFOSTS_TXEMPTYF_Msk) == 0) { /* Wait Tx empty and Time-out manner */
+			u32delayno++;
+			if(u32delayno >= 0x40000000)
+				return u32Count;
+		}
+		uart->DAT = pu8TxBuf[u32Count];    /* Send UART Data from buffer */
+	}
+	return u32Count;
 }
```
 So, Would you please check above code for your side and suggest if we have did anything wrong into driver code?

Regards,
Ritesh Prajapati

**Comment by dipenparmar** [comment]
Ideally,

Yachen,
We are okay to use the suggestion given by you and in our quick hook we have checked FIFO Empty status for some XXXX time (Based on various testing), so it will be really good if there is the best example related to your suggestion. 

BR,
Dipen

**Comment by yachen** [comment]
Something like:

```
while(remain) {
    ret = UART_Write(UART1, tx_buf, remain);
    tx_buf += ret;
    remain -= ret;
    // do other stuffs, let UART consumes Tx FIFO
}
```

**Comment by Ritesh236** [comment]
> Something like:
> 
> ```
> while(remain) {
>     ret = UART_Write(UART1, tx_buf, remain);
>     tx_buf += ret;
>     remain -= ret;
>     // do other stuffs, let UART consumes Tx FIFO
> }
> ```

Hi,

We will check that solution and let you know if any query or issue for that.

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
Close since there's no further discussion for a while. Reopen if necessary.
