### ISSUE TITLE
Failed to discover IP over DHCP when application run over External RAM

### ISSUE THREAD

**Issue by Ritesh236** [OpenNuvoton/NUC472_442BSP#4]
Hi ,

We have a requirement in our Gateway product which uses the NUC472.

The flash is loaded with two binaries i.e. bootloader at 0 location and application at 0x10000 location.
The bootloader boots up and initializes the hardware peripherals such as Clock, External SRAM via EBI etc.
Following the initialization, the Bootloader jumps to the application binary location in the flash.
The application code boots up completely on the external 512K SRAM (0x60000000).

Now, the application uses BSP along with FreeRTOS 8.2.1 and LWIP 1.4.1 implementations present as third party code with
the OpenNuvoton NUC472_442 BSP v03.00.00 GIT Repository.

We are using Ethernet for external connectivity for which we require to run DHClient. However, upon running
the DHClient, we are not able to obtain IP address from our gateway. Upon further investigation in LWIP/EMAC Driver
implementations, we found that the First DHCP Discover request returns success from the LWIP stack but has not
yet been transmitted by the EMAC.

This results into Tx Buffer not being available for consequent Tx triggers. Digging for information on similar cases on
various forums gave us a scenario in which DHCP was not working with External RAM as DMA engine is unable to
access non-contiguous RAM locations. We tried looking for such information in the Technical Reference Manual v1.05
but were not able to get some conclusive insight.

One noteworthy observation we made was that the Ethernet communication is working fine with static IP. Also DHCP
works when we loaded a demo application onto the internal 64k RAM. However, same application fails to get IP when
booted on external RAM.

Could you please consider this scenario with some urgency and provide help or insight into it? This is becoming critical for
our road map.

**Comment by yachen** [comment]
Hi,

EMAC cannot use external memory as Tx/Rx buffer.
e.g. eth_descriptor->buf must points to internal memory space.



Sincerely,

Yi-An Chen


===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

Thanks for your valuable feedback for same.

As I have explained earlier that we are planning to move FreeRTOS, BSP and rest components into External RAM and keep Internal RAM as it is for future usage as we need more memory for our custom components.

So, We have modified nuc472_eth.c file with below changes and  we are able to discover DHCP IP request without any issue.

1) moved rx_buf and tx_buf into Internal SRAM
2) keep rx_desc and tx_desc into External RAM as it is 

As you have mentioned into your reply like if we move rx_buf and tx_buf into External RAM then we are not able to get DHCP IP Discovery and call is going to failed while getting ETH_get_tx_buf();. So, We have also looked into NUvoton TRM and ARM Specific documents as well for this and found that EMAC buffers should be into contiguous internal RAM to access it.

Would you please let me know is there any other components or Interface we need to take care like EMAC TX & RX buffers to work into Internal Memory? Any DMA component or buffer? so that it will be helpful for us to save debugging time as well because we have already spent one week around to find this issue.

Let me know if you need any information from our side.

**Comment by Ritesh236** [comment]
Hi Yi-An Chen,

Would you please check last comments for same and provide your feedback for same?

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
Hi,

Don’t use external SRMA for high speed peripheral’s back end memory (e.g. EMAC, SD,  USB, image sensor).
Others are fine.


Sincerely,

Yi-An Chen


===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
[nuc472_eth.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701632/nuc472_eth.txt)

```
#define EMAC_BUFF_BASE        (0x20000000UL)

/* The EMAC Tx and Rx buffers need to be kept in the embedded SRAM
 * as the DMA engine is unable to access external RAM
 */
static u8_t *rx_buf = (u8_t *) EMAC_BUFF_BASE;
static u8_t *tx_buf = (u8_t *) (EMAC_BUFF_BASE + (RX_DESCRIPTOR_NUM * PACKET_BUFFER_SIZE));

```

As you  suggest, We modified EMAC Buffers to point into Internal RAM (0x20000000) and it worked for DHCP for sometimes. Though It failed in further communication after sometimes with below error which we have seen into debug logs.

> E dns: lwip_getaddrinfo: 302: lwip_getaddrinfo((null)) failed, err=-6

Can you suggest if we need to make any other changes into attached source code of EMAC Driver?

[gcc_arm_app.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701644/gcc_arm_app.txt)
[gcc_arm_bootloader.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701645/gcc_arm_bootloader.txt)
[startup_NUC472_442.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701646/startup_NUC472_442.txt)
[ethernetif.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701649/ethernetif.txt)
[bootloader.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701711/bootloader.txt)
[main.txt](https://github.com/OpenNuvoton/NUC472_442BSP/files/2701714/main.txt)

Please find attached bootloader linker, application linker, NUC472 Startup file and Ethernet IF Interface files which we are using into build for your reference purpose.

1. Bootloader uses only internal RAM in linker and initializes External RAM in main.c file 
2. Bootloader jumps to application at FLASH 0x10000
3. Application uses only External RAM in linker (Where initialization take place at boot loader)
4. All Application Data, BSS and Heap sections are under External RAM 
5. Only EMAC Driver (as shown above) directly referencing its buffers into Internal RAM

Any further suggestions to move from Ethernet perspective (including LWIP component)?

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
Where does following message comes from? I cannot find it in lwip source code.


E dns: lwip_getaddrinfo: 302: lwip_getaddrinfo((null)) failed, err=-6


===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by Ritesh236** [comment]
> Where does following message comes from? I cannot find it in lwip source code. E dns: lwip_getaddrinfo: 302: lwip_getaddrinfo((null)) failed, err=-6 =========================================================================================== The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

Hi, 

That is print is genuine message as we are not passing any port while resolving DNS from our custom service. So, We don't need to worry about that error message which is being generated due to our custom service.

> But, Ping is getting failed after sometimes (randomly) which can not be recovered except board restart.

Would you please check rest of points and suggest us best solution to move further for Ethernet Perspective?

Regards,
Ritesh Prajapati

**Comment by yachen** [comment]
nuc472_eth.txt assign EMAC buffer at the beginning of internal SRAM. However  I cannot find how you reserve the space for them in link file. Please check your map file to confirm no one else is using that space.

**Comment by yachen** [comment]
Close since there's no further discussion for a while. Reopen if necessary.
